import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useParams } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { apiRequest } from "@/lib/queryClient";

type ChangeOrder={id:number;description:string;amount:number;status:string;job_number:string;title:string;first_name:string;last_name:string;signer_name?:string};
export default function ChangeOrderPage(){const{token}=useParams<{token:string}>();const[name,setName]=useState("");const[acceptedTerms,setAcceptedTerms]=useState(false);const{data,isLoading,isError}=useQuery<ChangeOrder>({queryKey:["change-order",token],queryFn:async()=>{const r=await fetch(`/api/change-orders/${token}`,{credentials:"include"});if(!r.ok)throw new Error("Not found");return r.json();}});const respond=useMutation<{status:string;message:string},Error,"accepted"|"declined">({mutationFn:async(decision)=>{const r=await apiRequest(`/api/change-orders/${token}/respond`,"POST",{decision,signerName:name,acceptedTerms:decision==="accepted"?acceptedTerms:true});return r.json();}});if(isLoading)return <main className="min-h-screen bg-slate-50 p-6 pt-24 text-center">Loading Change Order…</main>;if(isError||!data)return <main className="min-h-screen bg-slate-50 p-6 pt-24 text-center text-red-700">This Change Order link is invalid or unavailable.</main>;return <main className="min-h-screen bg-slate-50 p-4 pt-16"><Card className="mx-auto max-w-2xl"><CardHeader><div className="flex justify-between gap-3"><div><CardTitle>Change Order</CardTitle><CardDescription>{data.job_number} · {data.title}</CardDescription></div><Badge className="capitalize">{respond.data?.status||data.status}</Badge></div></CardHeader><CardContent className="space-y-6"><div><p className="text-sm text-muted-foreground">Additional or revised work</p><p className="mt-2 whitespace-pre-wrap">{data.description}</p></div><div className="rounded-lg bg-slate-950 p-4 text-white"><p className="text-sm text-slate-300">Contract price adjustment</p><strong className="text-2xl">{Number(data.amount).toLocaleString("en-US",{style:"currency",currency:"USD"})}</strong></div>{respond.isSuccess?<div className="rounded-lg bg-emerald-50 p-4 text-emerald-900">{respond.data.message}</div>:data.status!=="sent"?<p>This Change Order is {data.status} and cannot be answered again.</p>:<><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/><label className="flex items-start gap-3 text-sm"><Checkbox checked={acceptedTerms} onCheckedChange={value=>setAcceptedTerms(value===true)}/><span>I understand that approving this Change Order changes the agreed work and contract price.</span></label>{respond.isError&&<p className="text-sm text-red-700">{respond.error.message}</p>}<div className="flex gap-3"><Button className="flex-1" disabled={name.length<2||!acceptedTerms||respond.isPending} onClick={()=>respond.mutate("accepted")}>Approve Change Order</Button><Button className="flex-1" variant="outline" disabled={name.length<2||respond.isPending} onClick={()=>respond.mutate("declined")}>Decline</Button></div></>}</CardContent></Card></main>}
