uploads = []
generated = []

[[outputs]]
id = "47yCsEhjb2QtixZoKtXfo"
uri = "file://handytech-deployment-2026-05-10.zip"
type = "unspecified"
title = "HandyTech Full Deployment - May 10, 2026"

[[outputs]]
id = "-ywKPzjjLaXebw5znGBXk"
uri = "file://handytech-dist-update.zip"
type = "unspecified"
title = "HandyTech - Built Files Update (606KB)"

[[outputs]]
id = "hvOR_BL8fg9aiVFErzn5J"
uri = "file://handytech-complete-20260513.zip"
type = "unspecified"
title = "HandyTech Complete Deployment (All Files)"
