uploads = []
generated = []

[[outputs]]
id = "47yCsEhjb2QtixZoKtXfo"
uri = "file://handytech-deployment-2026-05-10.zip"
type = "unspecified"
title = "HandyTech Full Deployment - May 10, 2026"

[[outputs]]
id = "-ywKPzjjLaXebw5znGBXk"
uri = "file://handytech-dist-update.zip"
type = "unspecified"
title = "HandyTech - Built Files Update (606KB)"
