export type ServiceSeoContent = { metaDescription: string; introduction: string; included: string[]; goodFor: string[]; process: string[] };

export const SERVICE_SEO_CONTENT: Record<string, ServiceSeoContent> = {
  "small-bathroom-remodel": {
    metaDescription: "Small bathroom remodeling in St. Louis, including vanity, toilet, lighting, drywall, painting, fixture replacement, and finish work.",
    introduction: "Update a small bathroom without coordinating several contractors. HandyTech can handle a practical group of improvements—from removing dated fixtures through final paint and cleanup—with one clear scope of work.",
    included: ["Vanity, sink, faucet, and toilet replacement", "Light fixture and hardware updates", "Minor drywall repair and surface preparation", "Painting, caulking, trim, and finishing details", "Removal of replaced fixtures and job-site cleanup"],
    goodFor: ["Guest and hallway bathrooms", "Rental-property refreshes", "Accessibility and safety improvements", "Preparing a home for sale", "Replacing worn or outdated fixtures"],
    process: ["Review the room, measurements, fixtures, and desired finish", "Confirm the work scope and materials before scheduling", "Protect nearby surfaces and remove selected fixtures", "Complete installation, repairs, painting, and finish work", "Test fixtures and walk through the completed bathroom"],
  },
  "multi-room-painting": {
    metaDescription: "Interior multi-room painting in St. Louis with wall preparation, trim work, careful protection, clean lines, and organized completion.",
    introduction: "Refresh several rooms with consistent preparation, color, and finish. HandyTech organizes the work room by room, protects floors and furnishings, repairs minor surface defects, and keeps the project manageable while your home remains occupied.",
    included: ["Protection for floors, furniture, and nearby surfaces", "Minor nail-hole and surface repair", "Wall and selected trim preparation", "Professional application with clean cut lines", "Room-by-room cleanup and final touchups"],
    goodFor: ["Whole-floor color updates", "Move-in or move-out painting", "Rental turnover preparation", "Refreshing high-traffic living spaces", "Coordinated walls and trim"],
    process: ["Confirm rooms, colors, sheen, and trim requirements", "Review repairs and areas needing extra preparation", "Set a room sequence that minimizes disruption", "Prepare, paint, inspect, and touch up each area", "Complete a final walkthrough before cleanup"],
  },
  "drywall-patch-small": {
    metaDescription: "Small drywall repair in St. Louis for holes, dents, anchors, and damaged wall areas, including patching, sanding, and finishing.",
    introduction: "Small wall damage is highly visible once light hits it. HandyTech repairs holes, dents, and damaged drywall with attention to blending the patch into the surrounding surface so it is ready for primer and paint.",
    included: ["Assessment of the damaged area and surrounding wall", "Removal of loose or compromised material", "Backing, patching, compound, and reinforcement as needed", "Sanding and feathering into the existing surface", "Primer-ready finish and work-area cleanup"],
    goodFor: ["TV-mount and anchor holes", "Door-handle damage", "Small plumbing access openings", "Dents, cracks, and failed patches", "Walls being prepared for repainting"],
    process: ["Inspect the damage and select the appropriate patch method", "Protect the immediate work area", "Patch, reinforce, and apply finishing compound", "Sand and inspect the transition under light", "Prepare the surface for primer and paint"],
  },
  "ceiling-fan-install": {
    metaDescription: "Ceiling fan installation in St. Louis with secure mounting, assembly, wiring, balancing, and complete function testing.",
    introduction: "A ceiling fan must be supported correctly and wired safely. HandyTech replaces compatible existing fixtures, assembles and mounts the fan, verifies operation, and checks for wobble or unusual noise before the job is complete.",
    included: ["Removal of the existing compatible light fixture", "Inspection of the visible mounting box and wiring", "Fan assembly and secure mounting", "Connection of controls, light kit, or remote when included", "Operation, direction, balance, and light testing"],
    goodFor: ["Bedrooms and living rooms", "Replacing dated ceiling fixtures", "Adding air movement to occupied spaces", "Remote-controlled fan upgrades", "Fans with integrated lighting"],
    process: ["Confirm the fan model and existing fixture location", "Inspect accessible support and wiring conditions", "Remove the old fixture and assemble the fan", "Mount, connect, and configure included controls", "Test all speeds, lighting, balance, and direction"],
  },
  "whole-home-smart-camera-system": {
    metaDescription: "Whole-home security camera installation in St. Louis with placement, mounting, cabling, recorder setup, and app configuration.",
    introduction: "A camera system works best when coverage, cable paths, recording, and remote access are planned together. HandyTech installs multi-camera systems with practical viewing angles and helps configure the recorder, network connection, and customer app.",
    included: ["Camera placement and coverage planning", "Mounting for seven or more compatible cameras", "Accessible low-voltage cable routing", "DVR or NVR connection and basic configuration", "Mobile app connection, viewing test, and customer orientation"],
    goodFor: ["Homes needing exterior perimeter coverage", "Detached garages and multiple entrances", "Replacing scattered stand-alone cameras", "Local recording with remote viewing", "Organized residential security upgrades"],
    process: ["Review coverage priorities, equipment, and recording goals", "Plan camera positions and practical cable routes", "Install cameras and complete accessible cabling", "Configure the recorder, network, and mobile access", "Test every view and show you how to use the system"],
  },
};

const standardProcess = (item: string): string[] => [
  `Review the ${item}, work area, and compatible customer-provided equipment`,
  "Confirm the scope, access requirements, and any visible concerns",
  "Protect the work area and remove the item being replaced when applicable",
  "Complete the installation or repair and make necessary adjustments",
  "Test the completed work and review operation with you",
];

Object.assign(SERVICE_SEO_CONTENT, {
  "faucet-replacement": {
    metaDescription: "Faucet replacement in St. Louis for kitchens, bathrooms, and utility sinks, including removal, connection, leak testing, and cleanup.",
    introduction: "Replace a leaking, worn, or outdated faucet with a compatible new fixture. HandyTech removes the existing faucet, connects the replacement, checks accessible shutoffs and supply connections, and tests for proper operation and leaks.",
    included: ["Removal of the existing compatible faucet", "Installation of a customer-selected replacement", "Connection to accessible existing supply lines", "Basic drain or pop-up connection when included", "Flow, function, and leak testing"],
    goodFor: ["Dripping or difficult-to-use faucets", "Kitchen and bathroom updates", "Rental-property fixture replacement", "Water-saving fixture upgrades", "Replacing corroded finishes"],
    process: standardProcess("faucet and plumbing connections"),
  },
  "single-room-painting": {
    metaDescription: "Single-room interior painting in St. Louis with minor wall preparation, careful protection, clean cut lines, trim options, and cleanup.",
    introduction: "Give one room a cleaner, more finished appearance without turning the whole home into a construction zone. HandyTech handles minor preparation, protects surrounding surfaces, and applies the selected wall and trim finishes carefully.",
    included: ["Floor and nearby-surface protection", "Minor nail-hole and surface preparation", "Wall painting in the selected color and sheen", "Trim painting when included in the scope", "Touchups and work-area cleanup"],
    goodFor: ["Bedrooms, offices, and living rooms", "Color changes and accent refreshes", "Move-in preparation", "Rental turnover", "Rooms repaired after minor wall damage"],
    process: standardProcess("room, surfaces, colors, and finish requirements"),
  },
  "toilet-swap": {
    metaDescription: "Toilet replacement in St. Louis with removal, wax-ring installation, connection, leveling, leak testing, and basic cleanup.",
    introduction: "Replace an aging or inefficient toilet with a compatible new unit. HandyTech removes the existing fixture, prepares the connection, installs and levels the replacement, reconnects the water supply, and tests for leaks and proper flushing.",
    included: ["Removal of the existing toilet", "New wax ring or compatible seal", "Placement, leveling, and secure mounting", "Connection to the accessible water supply", "Flush and leak testing"],
    goodFor: ["Cracked or frequently running toilets", "Bathroom refresh projects", "Water-efficient fixture upgrades", "Rental-property maintenance", "Replacing stained or outdated fixtures"],
    process: standardProcess("toilet, flange area, and supply connection"),
  },
  "vanity-sink-replacement": {
    metaDescription: "Bathroom vanity and sink replacement in St. Louis, including removal, placement, plumbing reconnection, faucet setup, sealing, and testing.",
    introduction: "A new vanity can improve storage, function, and the overall appearance of a bathroom. HandyTech replaces compatible vanity and sink assemblies, reconnects accessible plumbing, seals appropriate edges, and checks the finished installation.",
    included: ["Removal of the existing compatible vanity and top", "Placement and securing of the replacement vanity", "Sink, faucet, and drain assembly when included", "Reconnection to accessible plumbing", "Sealing, function testing, and cleanup"],
    goodFor: ["Small bathroom updates", "Damaged or swollen cabinetry", "Adding usable storage", "Rental and resale preparation", "Coordinating new fixtures and finishes"],
    process: standardProcess("vanity dimensions, wall condition, and plumbing layout"),
  },
  "dishwasher-install-replace": {
    metaDescription: "Dishwasher installation and replacement in St. Louis with removal, positioning, accessible plumbing and electrical connections, and testing.",
    introduction: "Replace a compatible built-in dishwasher and get it aligned, secured, and connected correctly. HandyTech handles the physical installation, accessible water and drain connections, available electrical connection, leveling, and a basic test cycle.",
    included: ["Removal of the existing compatible dishwasher", "Inspection of the accessible opening and connections", "Positioning, leveling, and securing the new unit", "Accessible supply, drain, and electrical connection", "Basic fill, drain, and leak testing"],
    goodFor: ["Direct appliance replacements", "Kitchen refresh projects", "Failed or leaking older units", "Rental-property appliance changes", "Upgrading to a quieter or efficient model"],
    process: standardProcess("dishwasher opening and utility connections"),
  },
  "light-fixture-replacement": {
    metaDescription: "Light fixture replacement in St. Louis for compatible ceiling and wall fixtures, including removal, mounting, wiring, assembly, and testing.",
    introduction: "Update a compatible ceiling or wall light with secure mounting and careful assembly. HandyTech removes the existing fixture, installs the replacement using accessible existing wiring, and confirms that the light and controls operate properly.",
    included: ["Removal of the existing compatible fixture", "Inspection of visible mounting and wiring conditions", "Assembly and secure mounting of the replacement", "Connection to accessible existing wiring", "Bulb, switch, and function testing"],
    goodFor: ["Dining, hallway, and bedroom updates", "Bathroom vanity lights", "Replacing damaged or dated fixtures", "Rental-property maintenance", "Coordinating fixtures after painting"],
    process: standardProcess("fixture, mounting location, and visible wiring"),
  },
  "over-the-range-microwave-install": {
    metaDescription: "Over-the-range microwave installation in St. Louis with removal, bracket mounting, cabinet attachment, electrical connection, and fit testing.",
    introduction: "An over-the-range microwave must align with the cabinet, mounting bracket, ventilation arrangement, and available power. HandyTech installs compatible replacement units and verifies that doors, controls, light, and fan operate correctly.",
    included: ["Removal of a compatible existing microwave when applicable", "Template and mounting-bracket placement", "Cabinet attachment and unit positioning", "Connection to the available electrical receptacle", "Door, light, fan, and control testing"],
    goodFor: ["Direct microwave replacements", "Kitchen appliance updates", "Replacing failed older units", "Rental-property appliance turnover", "Coordinated kitchen refreshes"],
    process: standardProcess("microwave dimensions, cabinet, power, and vent arrangement"),
  },
  "structured-cabling-low-voltage-runs": {
    metaDescription: "Residential structured cabling and low-voltage runs in St. Louis for Ethernet, data drops, cameras, media, and network equipment.",
    introduction: "Reliable wired connections can improve cameras, offices, access points, and entertainment systems. HandyTech plans practical low-voltage routes, installs compatible cable and terminations, labels connections, and tests completed runs.",
    included: ["Route planning through accessible areas", "Compatible low-voltage cable installation", "Wall plate, jack, or device-side termination", "Basic labeling and cable organization", "Continuity or connection testing"],
    goodFor: ["Home offices and Ethernet drops", "Wi-Fi access point backhaul", "Security-camera infrastructure", "Media and equipment locations", "Reducing reliance on wireless connections"],
    process: standardProcess("desired endpoints, equipment, and accessible cable routes"),
  },
  "home-theater-setup": {
    metaDescription: "Home theater setup in St. Louis with TV or projector mounting, speaker placement, component connection, cable organization, and configuration.",
    introduction: "Bring the screen, sound, sources, and controls together as one usable system. HandyTech mounts compatible equipment, organizes connections, configures basic settings, and walks you through everyday operation.",
    included: ["Equipment and room-layout review", "Compatible TV or projector mounting", "Speaker and component placement", "Source, sound, and display connections", "Basic configuration, testing, and customer orientation"],
    goodFor: ["Living-room media upgrades", "Dedicated theater spaces", "Soundbar and surround systems", "Projector and screen installations", "Cleaning up confusing cable layouts"],
    process: standardProcess("room layout, display, audio components, and sources"),
  },
  "multi-camera-install-3-6-units": {
    metaDescription: "Security camera installation for three to six cameras in St. Louis with placement, mounting, cabling, network connection, and app setup.",
    introduction: "Cover several important areas with a coordinated camera installation. HandyTech helps select practical viewing angles, mounts compatible devices, completes accessible cabling, and connects the system for local or mobile viewing.",
    included: ["Placement review for three to six cameras", "Secure mounting at accessible locations", "Compatible power or low-voltage cabling", "Network or recorder connection", "View testing and mobile app setup"],
    goodFor: ["Front, rear, and side entrance coverage", "Small homes and businesses", "Garage and driveway monitoring", "Upgrading from one camera", "Systems needing organized setup"],
    process: standardProcess("coverage priorities, camera equipment, and cable routes"),
  },
  "tv-wall-mount": {
    metaDescription: "TV wall mounting in St. Louis with placement planning, compatible bracket installation, secure mounting, leveling, and cable organization.",
    introduction: "Mount your television at a practical viewing height with a compatible bracket and clean alignment. HandyTech reviews the wall and equipment, installs the mount, secures and levels the TV, and organizes visible cables according to the selected scope.",
    included: ["Viewing-height and placement review", "Installation of a compatible customer-provided mount", "Secure TV attachment and leveling", "Connection of accessible source and power cables", "Basic cable organization and display testing"],
    goodFor: ["Living rooms and bedrooms", "Soundbar and media-console layouts", "Fixed, tilting, or compatible full-motion mounts", "Replacing furniture-based TV stands", "Cleaner entertainment spaces"],
    process: standardProcess("TV size, bracket, wall type, and viewing position"),
  },
  "smart-home-hub-setup": {
    metaDescription: "Smart-home hub setup in St. Louis with account connection, compatible device integration, room organization, automations, and app guidance.",
    introduction: "Bring compatible smart devices into one organized system. HandyTech connects and configures the hub, adds supported devices, creates practical names or rooms, tests basic routines, and shows you how to manage the setup.",
    included: ["Hub installation and network connection", "Account and mobile app setup", "Integration of compatible smart devices", "Room, device-name, and basic routine configuration", "Operation testing and customer orientation"],
    goodFor: ["Combining several smart-device brands", "New smart-home installations", "Voice-assistant organization", "Basic lighting and security routines", "Simplifying device control"],
    process: standardProcess("hub, network, accounts, and compatible devices"),
  },
  "furniture-assembly": {
    metaDescription: "Furniture assembly in St. Louis for compatible flat-pack desks, shelves, cabinets, beds, tables, and storage furniture.",
    introduction: "Get boxed furniture assembled carefully and positioned where you want it. HandyTech follows the manufacturer instructions, organizes hardware, completes assembly, checks alignment and stability, and cleans up packaging within the agreed scope.",
    included: ["Parts and hardware inventory", "Assembly using provided instructions", "Alignment and adjustment of doors or drawers", "Basic stability and function check", "Placement and packaging consolidation"],
    goodFor: ["Desks and office furniture", "Shelving and storage units", "Beds, tables, and seating", "Flat-pack cabinets", "Home and small-business setups"],
    process: standardProcess("furniture package, instructions, parts, and final location"),
  },
  "grab-bar-installation": {
    metaDescription: "Grab bar installation in St. Louis for bathrooms and other support locations, with placement review, secure mounting, and stability testing.",
    introduction: "Add support where it is most useful for entering, standing, or moving through a bathroom. HandyTech reviews placement and accessible wall structure, installs a compatible grab bar with appropriate mounting, and checks stability.",
    included: ["Placement and reach review", "Inspection for accessible structural support", "Layout and careful drilling", "Secure mounting with appropriate compatible hardware", "Stability check and cleanup"],
    goodFor: ["Tub and shower entrances", "Toilet-area support", "Aging-in-place improvements", "Recovery and mobility needs", "Improving bathroom confidence"],
    process: standardProcess("grab-bar location, wall surface, and available support"),
  },
  "garbage-disposal-install": {
    metaDescription: "Garbage disposal installation in St. Louis with removal, compatible sink mounting, plumbing and electrical reconnection, and leak testing.",
    introduction: "Replace a failed or noisy disposal with a compatible new unit. HandyTech removes the existing disposal, installs the replacement at the sink flange, reconnects accessible plumbing and power, and tests operation and leaks.",
    included: ["Removal of the existing compatible disposal", "Installation at the existing sink opening", "Accessible drain and dishwasher-hose connection", "Connection to available compatible power", "Operation, vibration, and leak testing"],
    goodFor: ["Failed or leaking disposals", "Noisy older units", "Kitchen sink updates", "Rental-property maintenance", "Compatible horsepower upgrades"],
    process: standardProcess("disposal, sink connection, drain, and available power"),
  },
  "smart-thermostat-install": {
    metaDescription: "Smart thermostat installation in St. Louis with compatible wiring connection, Wi-Fi setup, app configuration, and heating or cooling testing.",
    introduction: "Upgrade a compatible HVAC control to a connected thermostat. HandyTech installs the device using accessible existing wiring, connects it to Wi-Fi and the manufacturer app, and tests basic heating and cooling calls.",
    included: ["Compatibility review using visible wiring", "Removal of the existing thermostat", "Mounting and connection of the new device", "Wi-Fi and mobile app setup", "Basic heating, cooling, and control testing"],
    goodFor: ["Remote temperature control", "Schedule and energy-management features", "Replacing outdated thermostats", "Smart-home integration", "Vacation and rental-property monitoring"],
    process: standardProcess("thermostat, HVAC controls, visible wiring, and Wi-Fi"),
  },
  "smart-doorbell-install": {
    metaDescription: "Smart video doorbell installation in St. Louis with mounting, compatible wiring or power setup, Wi-Fi connection, app configuration, and testing.",
    introduction: "Add a connected view of your front entrance with a compatible video doorbell. HandyTech mounts and powers the device, connects it to Wi-Fi and the mobile app, adjusts the viewing angle, and tests alerts and live video.",
    included: ["Doorbell location and compatibility review", "Secure device or mounting-wedge installation", "Connection to compatible existing wiring or provided power", "Wi-Fi and mobile app configuration", "Video, notification, and chime testing when supported"],
    goodFor: ["Front-door package awareness", "Replacing a basic wired doorbell", "Remote visitor notifications", "Smart-home security additions", "Improving entrance visibility"],
    process: standardProcess("doorbell location, power, chime, Wi-Fi, and app"),
  },
  "smart-lock-install": {
    metaDescription: "Smart lock installation in St. Louis with compatible deadbolt replacement, alignment, calibration, app connection, code setup, and testing.",
    introduction: "Upgrade a compatible exterior door with keypad or app-based access. HandyTech installs and aligns the smart lock, calibrates its movement, connects supported features, and confirms that manual and electronic operation work smoothly.",
    included: ["Door, bore, and existing deadbolt compatibility review", "Removal of the existing compatible lock", "Smart-lock installation and alignment", "Calibration, app connection, and basic code setup", "Manual, keypad, and locking-cycle testing"],
    goodFor: ["Keypad entry", "Rental and guest access", "Remote lock monitoring", "Replacing worn deadbolts", "Smart-home access routines"],
    process: standardProcess("door, deadbolt opening, alignment, lock, and app"),
  },
  "wi-fi-router-mesh-setup": {
    metaDescription: "Wi-Fi router and mesh-network setup in St. Louis with equipment placement, modem connection, network configuration, updates, and coverage testing.",
    introduction: "Improve everyday connectivity with a properly placed and configured router or compatible mesh system. HandyTech connects the equipment, creates the network, updates settings, places mesh nodes, and checks coverage in important areas.",
    included: ["Router or mesh equipment placement review", "Connection to the existing modem or internet gateway", "Network name, security, and app configuration", "Mesh-node pairing and placement", "Connection and basic coverage testing"],
    goodFor: ["Dead zones and weak-room coverage", "New internet equipment", "Home offices and streaming", "Adding mesh nodes", "Organizing connected-home devices"],
    process: standardProcess("internet equipment, home layout, devices, and coverage needs"),
  },
  "security-camera-install-1-2-units": {
    metaDescription: "Installation of one or two security cameras in St. Louis with placement, mounting, power, Wi-Fi or recorder connection, and app setup.",
    introduction: "Add focused coverage at one or two important locations without installing a full system. HandyTech mounts compatible cameras, connects available power or cabling, configures network access, and tests the final view and notifications.",
    included: ["Placement and viewing-angle review", "Secure mounting for one or two compatible cameras", "Accessible power or low-voltage connection", "Wi-Fi, recorder, or app connection", "Live-view and notification testing"],
    goodFor: ["Front doors and driveways", "Garages and side entrances", "Adding coverage to an existing system", "Small homes and offices", "Monitoring one priority area"],
    process: standardProcess("coverage goal, camera equipment, power, and connectivity"),
  },
} satisfies Record<string, ServiceSeoContent>);
