import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Bot,CheckCircle2,ShieldAlert,XCircle } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
type Action={id:number;action_type:string;entity_type:string;entity_id?:string;risk_level:string;proposed_payload:Record<string,unknown>;prepared_by:string;created_at:string};
const fetchActions=async():Promise<Action[]>=>{const response=await fetch("/api/admin/os/automation-actions?status=prepared",{credentials:"include"});if(!response.ok)throw new Error("Automation queue could not be loaded");return response.json();};
export default function AutomationReviewCenter(){const qc=useQueryClient();const{toast}=useToast();const{data:actions=[],isLoading}=useQuery<Action[]>({queryKey:["/api/admin/os/automation-actions","prepared"],queryFn:fetchActions});const decide=useMutation({mutationFn:({id,decision}:{id:number;decision:"approved"|"rejected"})=>apiRequest(`/api/admin/os/automation-actions/${id}`,"PATCH",{decision}),onSuccess:(_,{decision})=>{qc.invalidateQueries({queryKey:["/api/admin/os/automation-actions"]});toast({title:`Automation ${decision}`,description:decision==="approved"?"Approval is recorded. Execution remains separately auditable.":"The prepared action will not be used."});}});return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Bot className="h-5 w-5"/>AI & Automation Review</CardTitle><CardDescription>AI may prepare work, but customer messages, pricing, contracts, schedules, invoices, payment actions, and publishing require owner approval.</CardDescription></CardHeader><CardContent className="space-y-3">{isLoading?<p className="py-8 text-center text-muted-foreground">Loading prepared actions...</p>:actions.map(action=><div key={action.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><strong>{action.action_type.replaceAll("_"," ")}</strong><Badge variant={action.risk_level==="high"?"destructive":"secondary"}>{action.risk_level} risk</Badge></div><span className="text-xs text-muted-foreground">{action.entity_type} {action.entity_id||""}</span></div><pre className="mt-3 max-h-48 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs">{JSON.stringify(action.proposed_payload,null,2)}</pre><div className="mt-3 flex gap-2"><Button size="sm" disabled={decide.isPending} onClick={()=>decide.mutate({id:action.id,decision:"approved"})}><CheckCircle2 className="mr-2 h-4 w-4"/>Approve</Button><Button size="sm" variant="outline" disabled={decide.isPending} onClick={()=>decide.mutate({id:action.id,decision:"rejected"})}><XCircle className="mr-2 h-4 w-4"/>Reject</Button></div></div>)}{!isLoading&&!actions.length&&<div className="flex items-center gap-3 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-900"><ShieldAlert className="h-5 w-5"/>No consequential automation is awaiting approval.</div>}</CardContent></Card>}
