import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BriefcaseBusiness, Download, Plus, RefreshCw, TrendingUp } from "lucide-react";
import type { Customer } from "@shared/schema";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

type JobRow = { id:number; customer_id:number; job_number:string; title:string; description?:string; address?:string; status:string; first_name:string; last_name:string; email:string; invoice_total:number|string; amount_paid:number|string; expenses:number|string; approved_changes:number|string };
type Summary = { billed:number; collected:number; outstanding:number; expenses:number; grossProfit:number; activeJobs:number; completedJobs:number };
const statuses = ["lead","quoted","approved","scheduled","in_progress","completed","invoiced","paid","closed"];
const money = (n:number|string) => Number(n || 0).toLocaleString("en-US", { style:"currency", currency:"USD" });

export default function BusinessOperationsManager({ customers }:{ customers:Customer[] }) {
  const qc = useQueryClient(); const { toast } = useToast();
  const [open,setOpen]=useState(false); const [customerId,setCustomerId]=useState(""); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [address,setAddress]=useState("");
  const [expenseJob,setExpenseJob]=useState<JobRow|null>(null); const [expenseDescription,setExpenseDescription]=useState(""); const [expenseAmount,setExpenseAmount]=useState(""); const [expenseCategory,setExpenseCategory]=useState("materials");
  const [changeJob,setChangeJob]=useState<JobRow|null>(null); const [changeDescription,setChangeDescription]=useState(""); const [changeAmount,setChangeAmount]=useState("");
  const { data:jobs=[] }=useQuery<JobRow[]>({queryKey:["/api/admin/operations/jobs"]});
  const { data:summary }=useQuery<Summary>({queryKey:["/api/admin/operations/summary"]});
  const refresh=()=>{qc.invalidateQueries({queryKey:["/api/admin/operations/jobs"]});qc.invalidateQueries({queryKey:["/api/admin/operations/summary"]});};
  const create=useMutation({mutationFn:()=>apiRequest("/api/admin/operations/jobs","POST",{customerId:Number(customerId),title,description,address}),onSuccess:()=>{refresh();setOpen(false);setTitle("");setDescription("");setAddress("");toast({title:"Job created"});},onError:(e:Error)=>toast({title:"Job not created",description:e.message,variant:"destructive"})});
  const update=useMutation({mutationFn:({id,status}:{id:number;status:string})=>apiRequest(`/api/admin/operations/jobs/${id}`,"PATCH",{status}),onSuccess:refresh});
  const sync=useMutation({mutationFn:async()=> (await apiRequest("/api/admin/operations/sync","POST",{})).json(),onSuccess:(d)=>{refresh();toast({title:"Records synchronized",description:`${d.imported} existing quote records added to Jobs.`});}});
  const addExpense=useMutation({mutationFn:()=>apiRequest(`/api/admin/operations/jobs/${expenseJob!.id}/expenses`,"POST",{category:expenseCategory,description:expenseDescription,amount:Number(expenseAmount)}),onSuccess:()=>{refresh();setExpenseJob(null);setExpenseDescription("");setExpenseAmount("");toast({title:"Expense recorded"});}});
  const addChange=useMutation({mutationFn:()=>apiRequest(`/api/admin/operations/jobs/${changeJob!.id}/change-orders`,"POST",{description:changeDescription,amount:Number(changeAmount)}),onSuccess:()=>{refresh();setChangeJob(null);setChangeDescription("");setChangeAmount("");toast({title:"Change order drafted",description:"It is saved with this job for review."});}});
  const selectedCustomer=useMemo(()=>customers.find(c=>String(c.id)===customerId),[customers,customerId]);
  return <div className="space-y-5">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">
      {[['Billed',summary?.billed],['Collected',summary?.collected],['Outstanding',summary?.outstanding],['Expenses',summary?.expenses],['Gross profit',summary?.grossProfit]].map(([label,value])=><Card key={String(label)}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold">{money(Number(value||0))}</p></CardContent></Card>)}
      <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">Active jobs</p><p className="mt-1 text-lg font-bold">{summary?.activeJobs||0}</p></CardContent></Card>
    </div>
    <Card><CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="flex items-center gap-2"><BriefcaseBusiness className="h-5 w-5"/>Jobs & Profitability</CardTitle><CardDescription>Move every job from lead to paid, with expenses and scope changes attached.</CardDescription></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>sync.mutate()} disabled={sync.isPending}><RefreshCw className="mr-2 h-4 w-4"/>Sync existing</Button><Button variant="outline" asChild><a href="/api/admin/operations/accounting.csv"><Download className="mr-2 h-4 w-4"/>Accounting CSV</a></Button><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="mr-2 h-4 w-4"/>New Job</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create job</DialogTitle><DialogDescription>Connect work to one existing customer.</DialogDescription></DialogHeader><div className="space-y-3"><Label>Customer</Label><Select value={customerId} onValueChange={v=>{setCustomerId(v);const c=customers.find(x=>String(x.id)===v);if(c)setAddress([c.street,c.city,[c.state,c.zip].filter(Boolean).join(' ')].filter(Boolean).join(', '));}}><SelectTrigger><SelectValue placeholder="Select customer"/></SelectTrigger><SelectContent>{customers.map(c=><SelectItem key={c.id} value={String(c.id)}>{c.firstName} {c.lastName} · {c.email}</SelectItem>)}</SelectContent></Select><Label>Job title</Label><Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Kitchen repairs"/><Label>Scope notes</Label><Textarea value={description} onChange={e=>setDescription(e.target.value)}/><Label>Service address</Label><Input value={address} onChange={e=>setAddress(e.target.value)}/><Button className="w-full" disabled={!selectedCustomer||title.trim().length<2||create.isPending} onClick={()=>create.mutate()}>Create Job</Button></div></DialogContent></Dialog></div></CardHeader>
      <CardContent><div className="space-y-3">{jobs.map(job=><div key={job.id} className="rounded-lg border p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong>{job.job_number}</strong><Badge variant="secondary">{job.status.replace('_',' ')}</Badge></div><h3 className="mt-1 font-semibold">{job.title}</h3><p className="text-sm text-muted-foreground">{job.first_name} {job.last_name} · {job.email}</p>{job.address&&<p className="text-sm text-muted-foreground">{job.address}</p>}</div><Select value={job.status} onValueChange={status=>update.mutate({id:job.id,status})}><SelectTrigger className="w-full lg:w-44"><SelectValue/></SelectTrigger><SelectContent>{statuses.map(s=><SelectItem key={s} value={s}>{s.replace('_',' ')}</SelectItem>)}</SelectContent></Select></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><div className="rounded bg-slate-50 p-2">Invoice <strong className="block">{money(job.invoice_total)}</strong></div><div className="rounded bg-slate-50 p-2">Collected <strong className="block">{money(job.amount_paid)}</strong></div><div className="rounded bg-slate-50 p-2">Expenses <strong className="block">{money(job.expenses)}</strong></div><div className="rounded bg-emerald-50 p-2">Job margin <strong className="block">{money(Number(job.amount_paid)-Number(job.expenses))}</strong></div></div><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setExpenseJob(job)}>Add expense</Button><Button size="sm" variant="outline" onClick={()=>setChangeJob(job)}>Draft change order</Button></div></div>)}{!jobs.length&&<div className="py-10 text-center text-muted-foreground"><TrendingUp className="mx-auto mb-2 h-8 w-8"/>No jobs yet. Sync existing records or create the first job.</div>}</div></CardContent></Card>
    <Dialog open={!!expenseJob} onOpenChange={v=>!v&&setExpenseJob(null)}><DialogContent><DialogHeader><DialogTitle>Add expense</DialogTitle><DialogDescription>{expenseJob?.job_number} · materials, labor, fuel, or fees</DialogDescription></DialogHeader><Select value={expenseCategory} onValueChange={setExpenseCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["materials","labor","fuel","fees","other"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Input value={expenseDescription} onChange={e=>setExpenseDescription(e.target.value)} placeholder="Receipt or purchase description"/><Input type="number" min="0.01" step="0.01" value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)} placeholder="Amount"/><Button disabled={expenseDescription.length<2||Number(expenseAmount)<=0} onClick={()=>addExpense.mutate()}>Save Expense</Button></DialogContent></Dialog>
    <Dialog open={!!changeJob} onOpenChange={v=>!v&&setChangeJob(null)}><DialogContent><DialogHeader><DialogTitle>Draft change order</DialogTitle><DialogDescription>{changeJob?.job_number} · record work outside the original scope.</DialogDescription></DialogHeader><Textarea value={changeDescription} onChange={e=>setChangeDescription(e.target.value)} placeholder="Describe the added or removed work"/><Input type="number" step="0.01" value={changeAmount} onChange={e=>setChangeAmount(e.target.value)} placeholder="Price adjustment (negative for credit)"/><Button disabled={changeDescription.length<2||!changeAmount} onClick={()=>addChange.mutate()}>Save Draft</Button></DialogContent></Dialog>
  </div>;
}
