import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Database, ShieldCheck } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

type Preflight={enabled:boolean;sourceCounts:Record<string,number>;requirement:string};
type Source={sourceTable:string;sourceTotal:number;automaticallyMatched:number;needsReview:number;unmatchedHistorical:number;accountedFor:number;lostDeleted:number};
type Report={generatedAt:string;sources:Source[];totals:{source:number;automaticallyMatched:number;needsReview:number;unmatchedHistorical:number;accountedFor:number;lostDeleted:number}};
type Match={id:number;source_table:string;source_id:string;target_table?:string|null;target_id?:string|null;classification:string;match_rule:string;confidence:number;review_status:string;notes?:string|null};

const getJson=async<T,>(url:string):Promise<T>=>{const response=await fetch(url,{credentials:"include"});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message||"Request failed");return response.json();};

export default function MigrationControlCenter(){
  const qc=useQueryClient();const{toast}=useToast();const[selected,setSelected]=useState<Match|null>(null);const[targetTable,setTargetTable]=useState("");const[targetId,setTargetId]=useState("");const[notes,setNotes]=useState("");
  const{data:preflight,isLoading}=useQuery<Preflight>({queryKey:["/api/admin/os/preflight"]});
  const{data:report}=useQuery<Report>({queryKey:["/api/admin/os/reconciliation"],enabled:preflight?.enabled===true,queryFn:()=>getJson("/api/admin/os/reconciliation")});
  const{data:matches=[]}=useQuery<Match[]>({queryKey:["/api/admin/os/matches","review"],enabled:preflight?.enabled===true,queryFn:()=>getJson("/api/admin/os/matches")});
  const resolve=useMutation({mutationFn:()=>apiRequest(`/api/admin/os/matches/${selected!.id}`,"PATCH",{targetTable,targetId,notes:notes||undefined}),onSuccess:()=>{qc.invalidateQueries({queryKey:["/api/admin/os/matches"]});qc.invalidateQueries({queryKey:["/api/admin/os/reconciliation"]});setSelected(null);toast({title:"Migration relationship resolved",description:"The source record remains intact and the reviewed relationship is now auditable."});}});
  const review=matches.filter(item=>item.classification!=="automatically_matched"||item.review_status!=="resolved");
  if(isLoading)return <Card><CardContent className="p-8 text-center text-muted-foreground">Loading migration safeguards...</CardContent></Card>;
  return <div className="space-y-5">
    <Card className="border-blue-200 bg-blue-50/60"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-blue-700"/>Data Migration Control Center</CardTitle><CardDescription>Every production record must be accounted for. Source records are preserved even when a new relationship cannot yet be determined.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap items-center gap-3"><Badge variant={preflight?.enabled?"default":"secondary"}>{preflight?.enabled?"Compatibility migration enabled":"Migration not activated"}</Badge><span className="text-sm">{preflight?.requirement}</span></div>{!preflight?.enabled&&<p className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950">The additive schema and backfill remain gated. Existing production routes and records continue operating unchanged until staging reconciliation and explicit activation.</p>}</CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Source records",report?.totals.source??sum(preflight?.sourceCounts)],["Automatically linked",report?.totals.automaticallyMatched??0],["Needs human review",(report?.totals.needsReview||0)+(report?.totals.unmatchedHistorical||0)],["Lost / deleted",report?.totals.lostDeleted??0]].map(([label,value],index)=><Card key={String(label)} className={index===3&&Number(value)>0?"border-red-500":""}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{Number(value).toLocaleString()}</p></CardContent></Card>)}</div>
    {report&&<Card><CardHeader><CardTitle>Reconciliation by source</CardTitle><CardDescription>Accounted for = automatically matched + needs review + unmatched historical. Release is blocked if lost/deleted is not zero.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left"><th className="p-2">Legacy source</th><th className="p-2 text-right">Before</th><th className="p-2 text-right">Auto-linked</th><th className="p-2 text-right">Review</th><th className="p-2 text-right">Preserved unmatched</th><th className="p-2 text-right">Accounted</th><th className="p-2 text-right">Lost</th></tr></thead><tbody>{report.sources.map(source=><tr key={source.sourceTable} className="border-b"><td className="p-2 font-medium">{source.sourceTable}</td>{[source.sourceTotal,source.automaticallyMatched,source.needsReview,source.unmatchedHistorical,source.accountedFor,source.lostDeleted].map((value,index)=><td key={index} className={`p-2 text-right ${index===5&&value>0?"font-bold text-red-700":""}`}>{value}</td>)}</tr>)}</tbody></table></CardContent></Card>}
    {preflight?.enabled&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="h-5 w-5"/>Review queue</CardTitle><CardDescription>Ambiguous records are never silently attached. Resolve only after checking the original record and proposed destination.</CardDescription></CardHeader><CardContent className="space-y-2">{review.slice(0,200).map(item=><button key={item.id} className="flex w-full items-center justify-between gap-3 rounded-lg border p-3 text-left hover:bg-slate-50" onClick={()=>{setSelected(item);setTargetTable(item.target_table||"");setTargetId(item.target_id||"");setNotes(item.notes||"");}}><div><strong>{item.source_table} #{item.source_id}</strong><p className="text-xs text-muted-foreground">{item.match_rule.replaceAll("_"," ")} · confidence {Math.round(Number(item.confidence||0)*100)}%</p></div><Badge variant={item.classification==="needs_review"?"destructive":"secondary"}>{item.classification.replaceAll("_"," ")}</Badge></button>)}{!review.length&&<div className="flex items-center gap-2 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-900"><CheckCircle2 className="h-5 w-5"/>No unresolved migration relationships.</div>}</CardContent></Card>}
    <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>Resolve migration relationship</DialogTitle><DialogDescription>{selected?.source_table} #{selected?.source_id}. This records a reviewed link; it does not delete or rewrite the source record.</DialogDescription></DialogHeader><div className="space-y-3"><div><Label>Target table</Label><Input value={targetTable} onChange={event=>setTargetTable(event.target.value)} placeholder="jobs"/></div><div><Label>Target ID</Label><Input value={targetId} onChange={event=>setTargetId(event.target.value)} placeholder="123"/></div><div><Label>Review notes</Label><Textarea value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Evidence used to confirm this relationship"/></div><div className="flex items-start gap-2 rounded-lg bg-amber-50 p-3 text-sm"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/>Confirm against the historical source before resolving. The decision is retained in the migration audit ledger.</div><Button className="w-full" disabled={!targetTable.trim()||!targetId.trim()||resolve.isPending} onClick={()=>resolve.mutate()}>Save reviewed relationship</Button></div></DialogContent></Dialog>
  </div>;
}

function sum(values?:Record<string,number>){return Object.values(values||{}).reduce((total,value)=>total+Number(value||0),0);}
