import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, CheckCircle2, CircleDollarSign, ClipboardList, FileText, Images, MapPin, MessageSquare, Plus, Receipt, UserRound, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { apiRequest } from "@/lib/queryClient";
import { createCsrfHeaders } from "@/lib/csrf";
import { useToast } from "@/hooks/use-toast";

type Workspace={project:any;quotes:any[];appointments:any[];invoices:any[];expenses:any[];changeOrders:any[];reviews:any[];gallery:any[];approvedScopes:any[];workLogs:any[];closeoutItems:any[];activity:any[];media:any[];financials:{originalContract:number;approvedChanges:number;currentContract:number;estimatedCosts:number;actualCosts:number;billed:number;collected:number;outstandingReceivables:number;unbilledContract:number;projectedGrossProfit:number;billedGrossProfit:number}};
const money=(value:number)=>Number(value||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
const date=(value:any)=>value?new Date(value).toLocaleString("en-US",{timeZone:"America/Chicago",dateStyle:"medium",timeStyle:"short"}):"Not yet";
const status=(value?:string)=>String(value||"pending").replaceAll("_"," ");

export default function ProjectWorkspace({jobId,onClose,onNavigate}:{jobId:number|null;onClose:()=>void;onNavigate?:(tab:string)=>void}) {
  const qc=useQueryClient();const {toast}=useToast();const [note,setNote]=useState("");const [entryType,setEntryType]=useState("field_note");const [worker,setWorker]=useState("");const [hours,setHours]=useState("");const[mediaFile,setMediaFile]=useState<File|null>(null);const[mediaStage,setMediaStage]=useState("progress");
  const {data,isLoading,isError}=useQuery<Workspace>({queryKey:["project-workspace",jobId],enabled:!!jobId,queryFn:async()=>{const r=await fetch(`/api/admin/operations/jobs/${jobId}/workspace`,{credentials:"include"});if(!r.ok)throw new Error("Project could not be loaded");return r.json();}});
  const refresh=()=>qc.invalidateQueries({queryKey:["project-workspace",jobId]});
  const addWork=useMutation({mutationFn:()=>apiRequest(`/api/admin/operations/jobs/${jobId}/work-logs`,"POST",{entryType,note,workerName:worker||undefined,laborHours:hours?Number(hours):undefined}),onSuccess:()=>{refresh();setNote("");setHours("");toast({title:"Work entry saved"});}});
  const initCloseout=useMutation({mutationFn:()=>apiRequest(`/api/admin/operations/jobs/${jobId}/closeout/initialize`,"POST",{}),onSuccess:refresh});
  const updateCloseout=useMutation({mutationFn:({id,completed}:{id:number;completed:boolean})=>apiRequest(`/api/admin/operations/jobs/${jobId}/closeout/${id}`,"PATCH",{completed}),onSuccess:refresh});
  const addMedia=useMutation({mutationFn:async()=>{const form=new FormData();if(mediaFile)form.append("media",mediaFile);form.append("stage",mediaStage);const headers=await createCsrfHeaders();const response=await fetch(`/api/admin/operations/jobs/${jobId}/media`,{method:"POST",headers,body:form,credentials:"include"});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message||"Media could not be saved");return response.json();},onSuccess:()=>{refresh();setMediaFile(null);toast({title:"Job media saved"});}});
  const customer=data?.project?.customer;
  return <Dialog open={!!jobId} onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[94vh] max-w-6xl overflow-y-auto p-0"><div className="border-b bg-slate-950 p-5 text-white"><DialogHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><DialogTitle className="text-xl text-white">{data?.project?.job_number||"Job Workspace"} · {data?.project?.title||"Loading"}</DialogTitle><DialogDescription className="mt-1 text-slate-300">Approved scope, field work, schedule, money, documentation, and closeout.</DialogDescription></div>{data&&<Badge className="bg-blue-500 text-white">{status(data.project.status)}</Badge>}</div></DialogHeader></div><div className="p-5">{isLoading?<p className="py-16 text-center text-muted-foreground">Loading the Job Workspace…</p>:isError||!data?<p className="py-16 text-center text-red-600">The Job Workspace could not be loaded.</p>:<><div className="mb-5 grid gap-3 md:grid-cols-[1.4fr_repeat(4,1fr)]"><div className="rounded-xl border bg-slate-50 p-4"><p className="flex items-center gap-2 font-semibold"><UserRound className="h-4 w-4"/>{customer.first_name} {customer.last_name}</p><p className="mt-1 text-sm">{customer.email}</p><p className="text-sm">{customer.phone||"No phone saved"}</p>{data.project.address&&<p className="mt-2 flex gap-1 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5 shrink-0"/>{data.project.address}</p>}</div>{[["Contract",data.financials.currentContract],["Billed",data.financials.billed],["Collected",data.financials.collected],["Receivable",data.financials.outstandingReceivables]].map(([label,value])=><div key={String(label)} className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-bold">{money(Number(value))}</p></div>)}</div><Tabs defaultValue="overview"><TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="scope">Scope</TabsTrigger><TabsTrigger value="work">Work</TabsTrigger><TabsTrigger value="schedule">Schedule</TabsTrigger><TabsTrigger value="money">Money</TabsTrigger><TabsTrigger value="files">Files & Photos</TabsTrigger><TabsTrigger value="closeout">Closeout</TabsTrigger></TabsList>
      <TabsContent value="overview" className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold"><ClipboardList className="h-4 w-4"/>Job summary</h3><p className="whitespace-pre-wrap text-sm">{data.project.description||"No scope notes have been added yet."}</p><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><Info label="Actual direct cost" value={money(data.financials.actualCosts)}/><Info label="Projected gross profit" value={money(data.financials.projectedGrossProfit)}/><Info label="Unbilled contract" value={money(data.financials.unbilledContract)}/><Info label="Next activity" value={data.appointments[0]?date(data.appointments[0].start_timestamptz):"Not scheduled"}/></div></section><section className="rounded-xl border p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold"><MessageSquare className="h-4 w-4"/>Activity</h3><div className="space-y-2">{data.activity.slice(0,10).map(x=><div key={x.id} className="flex justify-between gap-3 border-b pb-2 text-sm"><span>{x.summary}</span><span className="shrink-0 text-xs text-muted-foreground">{date(x.occurred_at)}</span></div>)}{!data.activity.length&&<p className="text-sm text-muted-foreground">No contextual activity yet.</p>}</div></section></TabsContent>
      <TabsContent value="scope"><section className="space-y-4 rounded-xl border p-4"><div><h3 className="font-semibold">Original Approved Scope</h3>{data.approvedScopes[0]?<div className="mt-2 rounded-lg bg-blue-50 p-3"><strong>{data.approvedScopes[0].proposal_snapshot?.quoteNumber}</strong><p>Approved {date(data.approvedScopes[0].approved_at)} · {money(data.approvedScopes[0].approved_price)}</p><p className="mt-2 whitespace-pre-wrap text-sm">{data.approvedScopes[0].proposal_snapshot?.notes||data.project.description}</p></div>:<p className="mt-2 text-sm text-muted-foreground">No immutable Approved Scope snapshot is linked yet.</p>}</div><div><h3 className="font-semibold">Change Orders</h3><div className="mt-2 space-y-2">{data.changeOrders.map(x=><div key={x.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{x.description}</span><span className="font-semibold">{money(x.amount)} · {status(x.status)}</span></div>)}{!data.changeOrders.length&&<p className="text-sm text-muted-foreground">No post-approval changes.</p>}</div></div></section></TabsContent>
      <TabsContent value="work" className="space-y-4"><section className="rounded-xl border p-4"><h3 className="font-semibold">Add field work</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Select value={entryType} onValueChange={setEntryType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[["field_note","Field note"],["measurement","Measurement"],["task","Task update"],["problem","Problem discovered"],["labor","Labor"]].map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><Input value={worker} onChange={e=>setWorker(e.target.value)} placeholder="Worker (optional)"/>{entryType==="labor"&&<Input type="number" min="0" step="0.25" value={hours} onChange={e=>setHours(e.target.value)} placeholder="Labor hours"/>}<Textarea className="sm:col-span-2" rows={5} value={note} onChange={e=>setNote(e.target.value)} placeholder="Voice or typed field notes, measurements, completed work, remaining tasks, or discovered problems"/><Button className="sm:col-span-2" disabled={addWork.isPending||(!note.trim()&&!hours)} onClick={()=>addWork.mutate()}><Plus className="mr-2 h-4 w-4"/>Save Work Entry</Button></div></section><div className="space-y-2">{data.workLogs.map(x=><div key={x.id} className="rounded-xl border p-4"><div className="flex justify-between"><Badge variant="outline">{status(x.entry_type)}</Badge><span className="text-xs text-muted-foreground">{date(x.created_at)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm">{x.note}</p>{x.labor_hours&&<p className="mt-1 text-sm font-medium">{x.labor_hours} labor hour(s){x.worker_name?` · ${x.worker_name}`:""}</p>}</div>)}{!data.workLogs.length&&<p className="rounded-xl border p-8 text-center text-muted-foreground">No field work recorded.</p>}</div></TabsContent>
      <TabsContent value="schedule"><div className="space-y-2">{data.appointments.map(x=><div key={x.id} className="rounded-xl border p-4"><div className="flex justify-between"><strong>{x.service_type}</strong><Badge>{status(x.status)}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{date(x.start_timestamptz||x.appointment_date)} · {status(x.schedule_kind||"appointment")}</p></div>)}{!data.appointments.length&&<p className="rounded-xl border p-8 text-center text-muted-foreground">No Job schedule item attached.</p>}<Button variant="outline" onClick={()=>onNavigate?.("appointments")}><CalendarDays className="mr-2 h-4 w-4"/>Add Work Block</Button></div></TabsContent>
      <TabsContent value="money" className="space-y-4"><div className="grid gap-2 sm:grid-cols-4"><Info label="Original contract" value={money(data.financials.originalContract)}/><Info label="Approved changes" value={money(data.financials.approvedChanges)}/><Info label="Current contract" value={money(data.financials.currentContract)}/><Info label="Direct costs" value={money(data.financials.actualCosts)}/></div><section><h3 className="mb-2 font-semibold">Invoices & Payments</h3><div className="space-y-2">{data.invoices.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border p-4"><div><strong>{x.invoice_number}</strong><p className="text-xs text-muted-foreground">Due {date(x.due_date)} · {status(x.status)}</p></div><div className="text-right"><strong>{money(x.total)}</strong><p className="text-xs text-muted-foreground">Collected {money(x.amount_paid)}</p></div></div>)}{!data.invoices.length&&<p className="rounded-xl border p-6 text-center text-muted-foreground">No invoice created.</p>}</div><Button className="mt-3" onClick={()=>onNavigate?.("invoices")}><CircleDollarSign className="mr-2 h-4 w-4"/>Create Job Invoice</Button></section><section><h3 className="mb-2 font-semibold">Direct Job Costs</h3>{data.expenses.map(x=><div key={x.id} className="mb-2 flex items-center justify-between rounded-xl border p-3"><span className="flex items-center gap-2"><Receipt className="h-4 w-4"/>{x.description}</span><strong>{money(x.amount)}</strong></div>)}</section></TabsContent>
      <TabsContent value="files" className="space-y-4"><section className="rounded-xl border p-4"><h3 className="font-semibold">Add Job photo</h3><div className="mt-3 flex flex-col gap-3 sm:flex-row"><Select value={mediaStage} onValueChange={setMediaStage}><SelectTrigger className="sm:w-48"><SelectValue/></SelectTrigger><SelectContent>{["site_visit","before","progress","change_order","completion","document","other"].map(x=><SelectItem key={x} value={x}>{status(x)}</SelectItem>)}</SelectContent></Select><Input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>setMediaFile(e.target.files?.[0]||null)}/><Button disabled={!mediaFile||addMedia.isPending} onClick={()=>addMedia.mutate()}>Upload</Button></div></section><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{data.media.map(x=><a key={x.id} href={x.url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border"><img src={x.url} alt={x.caption||x.stage} className="aspect-square w-full object-cover"/><div className="p-2 text-xs"><Badge variant="outline">{status(x.stage)}</Badge><p className="mt-1">{x.caption}</p></div></a>)}{data.gallery.map(x=><a key={`gallery-${x.id}`} href={x.image_url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-xl border"><img src={x.image_url} alt={x.title} className="aspect-square w-full object-cover"/><div className="p-2 text-xs"><Badge>Published</Badge><p className="mt-1">{x.title}</p></div></a>)}{!data.media.length&&!data.gallery.length&&<div className="col-span-full rounded-xl border p-10 text-center text-muted-foreground"><Images className="mx-auto mb-2 h-8 w-8"/>No Job media attached.</div>}</div></TabsContent>
      <TabsContent value="closeout"><section className="rounded-xl border p-4"><div className="flex items-center justify-between"><h3 className="flex items-center gap-2 font-semibold"><Wrench className="h-4 w-4"/>Guided closeout</h3>{!data.closeoutItems.length&&<Button size="sm" onClick={()=>initCloseout.mutate()}>Start Closeout</Button>}</div><div className="mt-3 space-y-2">{data.closeoutItems.map(item=><label key={item.id} className={`flex items-center gap-3 rounded-lg p-3 text-sm ${item.completed?"bg-emerald-50 text-emerald-900":"bg-amber-50 text-amber-950"}`}><Checkbox checked={item.completed} onCheckedChange={checked=>updateCloseout.mutate({id:item.id,completed:checked===true})}/><span className="flex-1">{item.label}</span>{item.completed&&<CheckCircle2 className="h-4 w-4"/>}</label>)}{!data.closeoutItems.length&&<p className="py-8 text-center text-muted-foreground">Start closeout when the approved work is substantially complete.</p>}</div></section></TabsContent>
    </Tabs></>}</div></DialogContent></Dialog>;
}

function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><p className="text-xs text-muted-foreground">{label}</p><strong className="mt-1 block">{value}</strong></div>}
