import { useQuery } from "@tanstack/react-query";
import { CalendarDays, CircleDollarSign, ClipboardList, FileText, Images, MapPin, MessageSquare, Receipt, UserRound, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Workspace = {
  project:any; quotes:any[]; appointments:any[]; invoices:any[]; expenses:any[]; changeOrders:any[]; reviews:any[]; gallery:any[];
  financials:{ billed:number; collected:number; costs:number; grossProfit:number; balance:number };
};
const money=(value:number)=>Number(value||0).toLocaleString("en-US",{style:"currency",currency:"USD"});
const date=(value:any)=>value?new Date(value).toLocaleString("en-US",{timeZone:"America/Chicago",dateStyle:"medium",timeStyle:"short"}):"Not yet";
const status=(value?:string)=>String(value||"pending").replaceAll("_"," ");

export default function ProjectWorkspace({jobId,onClose,onNavigate}:{jobId:number|null;onClose:()=>void;onNavigate?:(tab:string)=>void}) {
  const {data,isLoading,isError}=useQuery<Workspace>({queryKey:["project-workspace",jobId],enabled:!!jobId,queryFn:async()=>{const r=await fetch(`/api/admin/operations/jobs/${jobId}/workspace`,{credentials:"include"});if(!r.ok)throw new Error("Project could not be loaded");return r.json();}});
  const customer=data?.project?.customer;
  const timeline=data?[...data.quotes.map(x=>({at:x.sent_at||x.created_at,label:x.quote_number||"Quote request",kind:"Quote",state:x.proposal_status||x.status})),...data.appointments.map(x=>({at:x.start_timestamptz||x.created_at,label:x.service_type,kind:"Appointment",state:x.status})),...data.invoices.map(x=>({at:x.sent_at||x.issue_date,label:x.invoice_number,kind:"Invoice",state:x.status}))].sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime()):[];
  return <Dialog open={!!jobId} onOpenChange={open=>!open&&onClose()}><DialogContent className="max-h-[92vh] max-w-6xl overflow-y-auto p-0"><div className="border-b bg-slate-950 p-5 text-white"><DialogHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><DialogTitle className="text-xl text-white">{data?.project?.job_number||"Project workspace"} · {data?.project?.title||"Loading"}</DialogTitle><DialogDescription className="mt-1 text-slate-300">One place for the customer, scope, schedule, money, messages, and closeout.</DialogDescription></div>{data&&<Badge className="bg-blue-500 text-white">{status(data.project.status)}</Badge>}</div></DialogHeader></div>
    <div className="p-5">{isLoading?<p className="py-16 text-center text-muted-foreground">Loading the full project…</p>:isError||!data?<p className="py-16 text-center text-red-600">The project workspace could not be loaded.</p>:<>
      <div className="mb-5 grid gap-3 md:grid-cols-[1.4fr_repeat(4,1fr)]"><div className="rounded-xl border bg-slate-50 p-4"><p className="flex items-center gap-2 font-semibold"><UserRound className="h-4 w-4"/>{customer.first_name} {customer.last_name}</p><p className="mt-1 text-sm">{customer.email}</p><p className="text-sm">{customer.phone||"No phone saved"}</p>{data.project.address&&<p className="mt-2 flex gap-1 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5 shrink-0"/>{data.project.address}</p>}</div>{[["Billed",data.financials.billed],["Collected",data.financials.collected],["Costs",data.financials.costs],["Gross profit",data.financials.grossProfit]].map(([label,value])=><div key={String(label)} className="rounded-xl border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-xl font-bold">{money(Number(value))}</p></div>)}</div>
      <div className="mb-5 flex flex-wrap gap-2"><Button onClick={()=>onNavigate?.("quotes")}><FileText className="mr-2 h-4 w-4"/>Quotes</Button><Button variant="outline" onClick={()=>onNavigate?.("appointments")}><CalendarDays className="mr-2 h-4 w-4"/>Schedule</Button><Button variant="outline" onClick={()=>onNavigate?.("invoices")}><CircleDollarSign className="mr-2 h-4 w-4"/>Invoices</Button><Button variant="outline" onClick={()=>onNavigate?.("gallery")}><Images className="mr-2 h-4 w-4"/>Gallery</Button></div>
      <Tabs defaultValue="overview"><TabsList className="h-auto w-full justify-start overflow-x-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="scope">Scope</TabsTrigger><TabsTrigger value="schedule">Schedule</TabsTrigger><TabsTrigger value="costs">Costs</TabsTrigger><TabsTrigger value="billing">Billing</TabsTrigger><TabsTrigger value="closeout">Closeout</TabsTrigger></TabsList>
        <TabsContent value="overview" className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold"><ClipboardList className="h-4 w-4"/>Project summary</h3><p className="whitespace-pre-wrap text-sm">{data.project.description||"No scope notes have been added yet."}</p><div className="mt-4 flex flex-wrap gap-2"><Badge variant="outline">{data.quotes.length} quote(s)</Badge><Badge variant="outline">{data.appointments.length} appointment(s)</Badge><Badge variant="outline">{data.invoices.length} invoice(s)</Badge></div></section><section className="rounded-xl border p-4"><h3 className="mb-3 flex items-center gap-2 font-semibold"><MessageSquare className="h-4 w-4"/>Activity</h3><div className="space-y-3">{timeline.slice(0,8).map((x,i)=><div key={`${x.kind}-${i}`} className="flex items-center justify-between gap-3 border-b pb-2 text-sm"><div><strong>{x.kind}</strong><p className="text-muted-foreground">{x.label} · {date(x.at)}</p></div><Badge variant="secondary">{status(x.state)}</Badge></div>)}{!timeline.length&&<p className="text-sm text-muted-foreground">No activity recorded yet.</p>}</div></section></TabsContent>
        <TabsContent value="scope"><section className="rounded-xl border p-4"><h3 className="font-semibold">Scope and approved changes</h3><p className="mt-2 whitespace-pre-wrap text-sm">{data.project.description||"No scope notes."}</p><div className="mt-4 space-y-2">{data.changeOrders.map(x=><div key={x.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{x.description}</span><span className="font-semibold">{money(x.amount)} · {status(x.status)}</span></div>)}</div></section></TabsContent>
        <TabsContent value="schedule"><div className="space-y-2">{data.appointments.map(x=><div key={x.id} className="rounded-xl border p-4"><div className="flex justify-between"><strong>{x.service_type}</strong><Badge>{status(x.status)}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{date(x.start_timestamptz||x.appointment_date)}</p></div>)}{!data.appointments.length&&<p className="rounded-xl border p-8 text-center text-muted-foreground">No appointment attached.</p>}</div></TabsContent>
        <TabsContent value="costs"><div className="space-y-2">{data.expenses.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border p-4"><div><strong className="flex items-center gap-2"><Receipt className="h-4 w-4"/>{x.description}</strong><p className="text-xs text-muted-foreground">{x.category} · {x.vendor||"No vendor"} · {date(x.expense_date)}</p></div><strong>{money(x.amount)}</strong></div>)}{!data.expenses.length&&<p className="rounded-xl border p-8 text-center text-muted-foreground">No costs recorded.</p>}</div></TabsContent>
        <TabsContent value="billing"><div className="space-y-2">{data.invoices.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border p-4"><div><strong>{x.invoice_number}</strong><p className="text-xs text-muted-foreground">Due {date(x.due_date)} · {status(x.status)}</p></div><div className="text-right"><strong>{money(x.total)}</strong><p className="text-xs text-muted-foreground">Paid {money(x.amount_paid)}</p></div></div>)}{!data.invoices.length&&<p className="rounded-xl border p-8 text-center text-muted-foreground">No invoice created.</p>}</div></TabsContent>
        <TabsContent value="closeout"><section className="rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><Wrench className="h-4 w-4"/>Closeout checklist</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{[["Work marked complete",["completed","invoiced","paid","closed"].includes(data.project.status)],["Invoice created",data.invoices.length>0],["Balance paid",data.financials.balance<=0&&data.invoices.length>0],["Project photos added",data.gallery.length>0],["Customer review received",data.reviews.length>0]].map(([label,done])=><div key={String(label)} className={`rounded-lg p-3 text-sm ${done?"bg-emerald-50 text-emerald-800":"bg-amber-50 text-amber-900"}`}>{done?"✓":"○"} {label}</div>)}</div></section></TabsContent>
      </Tabs></>}</div></DialogContent></Dialog>;
}
