import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bot, MailCheck, Plus, RefreshCw, ShieldCheck } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

type Rule = { id: number; name: string; service_pattern: string; enabled: boolean; response_mode: "draft" | "trusted"; response_template: string; minimum_score: number; max_lead_cost_points: number | null; allowed_zip_prefixes: string[] | null; excluded_terms: string[] | null };
type Event = { id: number; subject: string; sender: string; status: string; received_at: string; error?: string | null };
type Data = { rules: Rule[]; events: Event[]; mailboxEnabled: boolean };
type Form = { id?: number; name: string; servicePattern: string; enabled: boolean; responseMode: "draft" | "trusted"; responseTemplate: string; minimumScore: number; maxLeadCostPoints: string; allowedZipPrefixes: string; excludedTerms: string };
const blank: Form = { name: "", servicePattern: "", enabled: false, responseMode: "draft", responseTemplate: "Hi {{customer_name}}, this is Luis with HandyTech Solutions. Thank you for contacting us about your {{service}} project. Please send any available photos and your preferred timeframe.", minimumScore: 75, maxLeadCostPoints: "40", allowedZipPrefixes: "631, 630", excludedTerms: "gas line, service panel, asbestos, mold remediation, major structural" };

export default function ReferralAutomationSettings() {
  const [editing, setEditing] = useState<Form | null>(null); const qc = useQueryClient(); const { toast } = useToast();
  const { data } = useQuery<Data>({ queryKey: ["/api/admin/referral-automation"] });
  const refresh = () => qc.invalidateQueries({ queryKey: ["/api/admin/referral-automation"] });
  const save = useMutation({ mutationFn: async (form: Form) => { const payload = { name: form.name, servicePattern: form.servicePattern, enabled: form.enabled, responseMode: form.responseMode, responseTemplate: form.responseTemplate, minimumScore: Number(form.minimumScore), maxLeadCostPoints: form.maxLeadCostPoints ? Number(form.maxLeadCostPoints) : null, allowedZipPrefixes: form.allowedZipPrefixes.split(",").map((x) => x.trim()).filter(Boolean), excludedTerms: form.excludedTerms.split(",").map((x) => x.trim()).filter(Boolean) }; return (await apiRequest(form.id ? `/api/admin/referral-automation/rules/${form.id}` : "/api/admin/referral-automation/rules", form.id ? "PATCH" : "POST", payload)).json(); }, onSuccess: () => { refresh(); setEditing(null); toast({ title: "Automation rule saved" }); }, onError: (error: Error) => toast({ title: "Rule not saved", description: error.message, variant: "destructive" }) });
  const poll = useMutation({ mutationFn: () => apiRequest("/api/admin/referral-automation/poll", "POST", {}), onSuccess: () => { toast({ title: "Mailbox check started" }); setTimeout(refresh, 4000); } });
  const edit = (rule: Rule): Form => ({ id: rule.id, name: rule.name, servicePattern: rule.service_pattern, enabled: rule.enabled, responseMode: rule.response_mode, responseTemplate: rule.response_template, minimumScore: rule.minimum_score, maxLeadCostPoints: rule.max_lead_cost_points == null ? "" : String(rule.max_lead_cost_points), allowedZipPrefixes: (rule.allowed_zip_prefixes || []).join(", "), excludedTerms: (rule.excluded_terms || []).join(", ") });
  return <div className="space-y-4">
    <Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="flex items-center gap-2"><Bot className="h-5 w-5"/>IONOS lead automation</CardTitle><CardDescription>Import verified Home Depot mail automatically. Customer replies remain drafts unless an enabled rule is explicitly set to Trusted.</CardDescription></div><div className="flex gap-2"><Button variant="outline" onClick={() => poll.mutate()} disabled={poll.isPending}><RefreshCw className="mr-2 h-4 w-4"/>Check mailbox</Button><Button onClick={() => setEditing({...blank})}><Plus className="mr-2 h-4 w-4"/>Add approved service</Button></div></div></CardHeader><CardContent><div className="flex items-center gap-2 text-sm"><MailCheck className="h-4 w-4 text-emerald-700"/><span>{data?.mailboxEnabled !== false ? "Mailbox polling is enabled." : "Mailbox polling is disabled by server configuration."}</span></div></CardContent></Card>
    <div className="grid gap-3">{data?.rules.map((rule) => <Card key={rule.id}><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong>{rule.name}</strong><Badge variant={rule.enabled ? "default" : "secondary"}>{rule.enabled ? "Enabled" : "Disabled"}</Badge><Badge variant={rule.response_mode === "trusted" ? "destructive" : "outline"}>{rule.response_mode === "trusted" ? "Trusted auto-response" : "Draft only"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">Matches /{rule.service_pattern}/i · minimum {rule.minimum_score}%{rule.max_lead_cost_points != null ? ` · max ${rule.max_lead_cost_points} points` : ""}</p></div><Button variant="outline" onClick={() => setEditing(edit(rule))}>Edit rule</Button></CardContent></Card>)}{!data?.rules.length && <Card><CardContent className="py-8 text-center text-muted-foreground">No service is approved for automated responses yet. Mail can still be imported and reviewed safely.</CardContent></Card>}</div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/>Recent mailbox activity</CardTitle></CardHeader><CardContent className="space-y-2">{data?.events.map((event) => <div key={event.id} className="flex flex-col gap-1 rounded border p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{event.subject}</p><p className="text-xs text-muted-foreground">{event.sender} · {new Date(event.received_at).toLocaleString()}</p>{event.error && <p className="text-xs text-red-700">{event.error}</p>}</div><Badge variant="outline">{event.status.replaceAll("_", " ")}</Badge></div>)}{!data?.events.length && <p className="py-6 text-center text-sm text-muted-foreground">No Home Depot notification email has been processed yet.</p>}</CardContent></Card>
    <Dialog open={!!editing} onOpenChange={(open) => !open && setEditing(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{editing?.id ? "Edit" : "Add"} approved-service rule</DialogTitle><DialogDescription>Trusted mode may send this exact template automatically when every limit passes. Start in Draft mode.</DialogDescription></DialogHeader>{editing && <div className="space-y-3"><div><Label>Rule name</Label><Input value={editing.name} onChange={(e) => setEditing({...editing,name:e.target.value})} placeholder="Furniture assembly"/></div><div><Label>Service matching pattern</Label><Input value={editing.servicePattern} onChange={(e) => setEditing({...editing,servicePattern:e.target.value})} placeholder="assembly|cabinet installation"/></div><div className="grid gap-3 sm:grid-cols-3"><div><Label>Response mode</Label><Select value={editing.responseMode} onValueChange={(value: "draft"|"trusted") => setEditing({...editing,responseMode:value})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">Draft only</SelectItem><SelectItem value="trusted">Trusted auto-send</SelectItem></SelectContent></Select></div><div><Label>Minimum score</Label><Input type="number" min="0" max="100" value={editing.minimumScore} onChange={(e) => setEditing({...editing,minimumScore:Number(e.target.value)})}/></div><div><Label>Maximum points</Label><Input type="number" min="0" value={editing.maxLeadCostPoints} onChange={(e) => setEditing({...editing,maxLeadCostPoints:e.target.value})}/></div></div><div><Label>Allowed ZIP prefixes</Label><Input value={editing.allowedZipPrefixes} onChange={(e) => setEditing({...editing,allowedZipPrefixes:e.target.value})} placeholder="631, 630"/></div><div><Label>Excluded words or phrases</Label><Input value={editing.excludedTerms} onChange={(e) => setEditing({...editing,excludedTerms:e.target.value})}/></div><div><Label>Response template</Label><Textarea rows={6} value={editing.responseTemplate} onChange={(e) => setEditing({...editing,responseTemplate:e.target.value})}/><p className="text-xs text-muted-foreground">Available placeholders: {"{{customer_name}}"} and {"{{service}}"}.</p></div><label className="flex items-center justify-between rounded border p-3"><span><strong>Enable this rule</strong><span className="block text-xs text-muted-foreground">Disabled rules never prepare or send a response.</span></span><Switch checked={editing.enabled} onCheckedChange={(enabled) => setEditing({...editing,enabled})}/></label><Button className="w-full" onClick={() => save.mutate(editing)} disabled={save.isPending || editing.name.length < 2 || !editing.servicePattern || editing.responseTemplate.length < 10}>{save.isPending ? "Saving…" : "Save rule"}</Button></div>}</DialogContent></Dialog>
  </div>;
}
