import {useState} from "react";
import {useMutation,useQuery} from "@tanstack/react-query";
import {CalendarDays,Camera,Calculator,MessageSquare,NotebookPen,Send} from "lucide-react";
import {apiRequest} from "@/lib/queryClient";
import {createCsrfHeaders} from "@/lib/csrf";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Textarea} from "@/components/ui/textarea";
import {useToast} from "@/hooks/use-toast";

export default function RequestActions({requestId,refresh}:{requestId:number;refresh:()=>void}){const{toast}=useToast();const{data:proposalData}=useQuery<{proposals:any[]}>({queryKey:["request-workspace",requestId],queryFn:async()=>{const response=await fetch(`/api/admin/os/requests/${requestId}`,{credentials:"include"});if(!response.ok)throw new Error("Request could not be loaded");return response.json();}});const proposals=proposalData?.proposals||[];const[note,setNote]=useState("");const[question,setQuestion]=useState("");const[subject,setSubject]=useState("");const[visitStart,setVisitStart]=useState("");const[visitMinutes,setVisitMinutes]=useState("60");const[file,setFile]=useState<File|null>(null);const[laborHours,setLaborHours]=useState("");const[laborCost,setLaborCost]=useState("");const[otherCost,setOtherCost]=useState("");const[contingency,setContingency]=useState("");const[margin,setMargin]=useState("35");const[sellingPrice,setSellingPrice]=useState("");const[scope,setScope]=useState("");const[price,setPrice]=useState("");const[deposit,setDeposit]=useState("");const[duration,setDuration]=useState("To be scheduled after approval");const[included,setIncluded]=useState("");const[excluded,setExcluded]=useState("");
  const done=(title:string)=>{refresh();toast({title});};
  const addNote=useMutation({mutationFn:()=>apiRequest(`/api/admin/os/requests/${requestId}/activities`,"POST",{kind:"internal_note",body:note}),onSuccess:()=>{setNote("");done("Internal note added");}});
  const ask=useMutation({mutationFn:()=>apiRequest(`/api/admin/os/requests/${requestId}/activities`,"POST",{kind:"customer_question",subject:subject||undefined,body:question}),onSuccess:()=>{setQuestion("");setSubject("");done("Question sent and recorded");}});
  const visit=useMutation({mutationFn:()=>apiRequest(`/api/admin/os/requests/${requestId}/site-visits`,"POST",{start:new Date(visitStart).toISOString(),durationMinutes:Number(visitMinutes)}),onSuccess:()=>{setVisitStart("");done("Site visit scheduled");}});
  const estimate=useMutation({mutationFn:()=>apiRequest(`/api/admin/os/requests/${requestId}/estimates`,"POST",{estimatedLaborHours:Number(laborHours||0),internalLaborCost:Number(laborCost||0),contingency:Number(contingency||0),targetMarginPercent:Number(margin||0),ownerSelectedPrice:sellingPrice?Number(sellingPrice):undefined,items:Number(otherCost)>0?[{category:"other_direct_cost",description:"Materials and other direct costs",quantity:1,unitCost:Number(otherCost)}]:[]}),onSuccess:()=>done("Internal estimate saved")});
  const upload=useMutation({mutationFn:async()=>{const form=new FormData();if(file)form.append("media",file);form.append("stage","site_visit");const headers=await createCsrfHeaders();const response=await fetch(`/api/admin/os/requests/${requestId}/media`,{method:"POST",headers,body:form,credentials:"include"});if(!response.ok)throw new Error((await response.json().catch(()=>null))?.message||"File could not be saved");return response.json();},onSuccess:()=>{setFile(null);done("Request media added");}});
  const proposal=useMutation({mutationFn:()=>apiRequest(`/api/admin/os/requests/${requestId}/proposals`,"POST",{scope,price:Number(price),depositRequired:Number(deposit||0),approximateDuration:duration,includedWork:included,excludedWork:excluded,validDays:14}),onSuccess:()=>done("Proposal draft saved")});
  const draft=proposals.find(item=>item.status==="draft");
  const sendProposal=useMutation({mutationFn:()=>apiRequest(`/api/admin/os/requests/${requestId}/proposals/${draft.id}/send`,"POST",{}),onSuccess:()=>done("Proposal sent and recorded")});
  return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><NotebookPen className="h-4 w-4"/>Internal note</CardTitle></CardHeader><CardContent className="space-y-2"><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Private observations, measurements, or next steps"/><Button size="sm" disabled={note.trim().length<2||addNote.isPending} onClick={()=>addNote.mutate()}>Save Note</Button></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><MessageSquare className="h-4 w-4"/>Ask customer</CardTitle></CardHeader><CardContent className="space-y-2"><Input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Email subject (optional)"/><Textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What information do you need?"/><Button size="sm" disabled={question.trim().length<2||ask.isPending} onClick={()=>ask.mutate()}><Send className="mr-2 h-4 w-4"/>Send & Record</Button></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-4 w-4"/>Site visit</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><div><Label>Start</Label><Input type="datetime-local" value={visitStart} onChange={e=>setVisitStart(e.target.value)}/></div><div><Label>Minutes</Label><Input type="number" min="15" step="15" value={visitMinutes} onChange={e=>setVisitMinutes(e.target.value)}/></div><Button className="sm:col-span-2" size="sm" disabled={!visitStart||Number(visitMinutes)<15||visit.isPending} onClick={()=>visit.mutate()}>Schedule Site Visit</Button></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Camera className="h-4 w-4"/>Photos & files</CardTitle></CardHeader><CardContent className="space-y-2"><Input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/><Button size="sm" disabled={!file||upload.isPending} onClick={()=>upload.mutate()}>Add to Request</Button></CardContent></Card>
    <Card className="lg:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Calculator className="h-4 w-4"/>Internal estimate</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-3"><Field label="Estimated labor hours" value={laborHours} set={setLaborHours}/><Field label="Internal labor cost" value={laborCost} set={setLaborCost}/><Field label="Other direct costs" value={otherCost} set={setOtherCost}/><Field label="Contingency" value={contingency} set={setContingency}/><Field label="Target margin %" value={margin} set={setMargin}/><Field label="Owner-selected price" value={sellingPrice} set={setSellingPrice}/><Button className="sm:col-span-3" disabled={estimate.isPending} onClick={()=>estimate.mutate()}>Save Private Estimate</Button></div></CardContent></Card>
    <Card className="lg:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Send className="h-4 w-4"/>Customer proposal</CardTitle></CardHeader><CardContent className="space-y-3">{draft?<div className="flex flex-col justify-between gap-3 rounded-lg bg-blue-50 p-4 sm:flex-row sm:items-center"><div><strong>{draft.quote_number}</strong><p className="text-sm">Draft total: {Number(draft.total).toLocaleString("en-US",{style:"currency",currency:"USD"})}</p></div><Button disabled={sendProposal.isPending} onClick={()=>sendProposal.mutate()}><Send className="mr-2 h-4 w-4"/>Send Proposal</Button></div>:proposals.some(item=>item.status!=="draft")?<p className="rounded-lg bg-slate-50 p-4 text-sm">Proposal {proposals[0].quote_number} is {String(proposals[0].status).replaceAll("_"," ")}. Its approved history is preserved.</p>:<><Textarea value={scope} onChange={e=>setScope(e.target.value)} rows={4} placeholder="Clear customer-facing scope of work"/><div className="grid gap-3 sm:grid-cols-3"><Field label="Fixed price" value={price} set={setPrice}/><Field label="Deposit required" value={deposit} set={setDeposit}/><div><Label>Approximate duration</Label><Input value={duration} onChange={e=>setDuration(e.target.value)}/></div></div><Textarea value={included} onChange={e=>setIncluded(e.target.value)} placeholder="Included work"/><Textarea value={excluded} onChange={e=>setExcluded(e.target.value)} placeholder="Excluded work and assumptions"/><Button disabled={scope.trim().length<2||Number(price)<=0||proposal.isPending} onClick={()=>proposal.mutate()}>Create Proposal Draft</Button></>}</CardContent></Card></div>;
}
function Field({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return <div><Label>{label}</Label><Input type="number" min="0" step="0.01" value={value} onChange={e=>set(e.target.value)}/></div>}
