import { useQuery } from "@tanstack/react-query";
import { AlertCircle, CalendarDays, ClipboardList, FileSignature, MessageSquare, Receipt, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card";

type Item={kind:string;id:number;subtype:string;identity?:string;title:string;due_at?:string;job_id?:number;request_id?:number;first_name?:string;last_name?:string};
type Today={enabled:boolean;generatedAt?:string;items:Item[]};
type Capacity={day:string;available_hours:number|string;sold_hours:number|string;remaining_hours:number|string};
const icons:Record<string,any>={schedule:CalendarDays,request:ClipboardList,proposal:FileSignature,message:MessageSquare,invoice:Receipt,closeout:Wrench};
const labels:Record<string,string>={schedule:"Today's schedule",request:"Requests needing action",proposal:"Proposals awaiting action",message:"Messages needing reply",invoice:"Invoices due",closeout:"Jobs ready for closeout"};
const targets:Record<string,string>={schedule:"calendar",request:"requests",proposal:"requests",message:"live-chat",invoice:"money",closeout:"jobs"};
const fetchJson=async<T,>(url:string):Promise<T>=>{const r=await fetch(url,{credentials:"include"});if(!r.ok)throw new Error("Today could not be loaded");return r.json();};
export default function TodayCommandCenter({onNavigate}:{onNavigate:(tab:string)=>void}){
  const{data,isLoading}=useQuery<Today>({queryKey:["/api/admin/os/today"],queryFn:()=>fetchJson("/api/admin/os/today")});
  const{data:capacity=[]}=useQuery<Capacity[]>({queryKey:["/api/admin/os/scheduling/capacity"],enabled:data?.enabled===true,queryFn:()=>fetchJson("/api/admin/os/scheduling/capacity")});
  if(isLoading)return <Card><CardContent className="p-12 text-center text-muted-foreground">Loading what needs attention...</CardContent></Card>;
  if(!data?.enabled)return <Card className="border-amber-300"><CardHeader><CardTitle>Today at HandyTech</CardTitle><CardDescription>The lifecycle command center becomes active with the additive operating-system migration. Existing operational screens remain available below.</CardDescription></CardHeader></Card>;
  const groups=Object.entries(labels).map(([kind,label])=>({kind,label,items:data.items.filter(item=>item.kind===kind)}));
  const todayCapacity=capacity[0];
  return <div className="space-y-5"><Card className="border-slate-800 bg-slate-950 text-white"><CardHeader><CardTitle>Today at HandyTech</CardTitle><CardDescription className="text-slate-300">Operational work requiring attention, linked to its Request, Job, schedule, or financial context.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{groups.map(group=>{const Icon=icons[group.kind]||AlertCircle;return <button key={group.kind} onClick={()=>onNavigate(targets[group.kind])} className="rounded-xl border border-slate-700 bg-slate-900 p-4 text-left hover:border-blue-400"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-blue-300"/><strong className="text-2xl">{group.items.length}</strong></div><p className="mt-3 text-sm text-slate-200">{group.label}</p></button>;})}</CardContent></Card>
    {todayCapacity&&<Card><CardHeader><CardTitle>Capacity</CardTitle><CardDescription>Labor-hours committed compared with currently configured capacity.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3"><Metric label="Available today" value={`${Number(todayCapacity.available_hours).toFixed(1)} hrs`}/><Metric label="Scheduled demand" value={`${Number(todayCapacity.sold_hours).toFixed(1)} hrs`}/><Metric label="Remaining" value={`${Number(todayCapacity.remaining_hours).toFixed(1)} hrs`} danger={Number(todayCapacity.remaining_hours)<0}/></CardContent></Card>}
    <div className="grid gap-4 lg:grid-cols-2">{groups.map(group=>{const Icon=icons[group.kind]||AlertCircle;return <Card key={group.kind}><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle className="flex items-center gap-2 text-base"><Icon className="h-4 w-4"/>{group.label}</CardTitle><CardDescription>{group.items.length} item{group.items.length===1?"":"s"}</CardDescription></div><Button size="sm" variant="outline" onClick={()=>onNavigate(targets[group.kind])}>Open</Button></CardHeader><CardContent className="space-y-2">{group.items.slice(0,8).map(item=><div key={`${item.kind}-${item.id}`} className="flex items-start justify-between gap-3 rounded-lg border p-3"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">{item.identity||item.title}</strong><Badge variant="outline">{String(item.subtype||item.kind).replaceAll("_"," ")}</Badge></div><p className="mt-1 text-sm">{item.title}</p><p className="text-xs text-muted-foreground">{[item.first_name,item.last_name].filter(Boolean).join(" ")}{item.due_at?` · ${new Date(item.due_at).toLocaleString()}`:""}</p></div></div>)}{!group.items.length&&<p className="py-5 text-center text-sm text-muted-foreground">Nothing waiting here.</p>}</CardContent></Card>;})}</div>
  </div>;
}
function Metric({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className={`rounded-lg p-4 ${danger?"bg-red-50 text-red-900":"bg-slate-50"}`}><p className="text-xs opacity-70">{label}</p><strong className="mt-1 block text-xl">{value}</strong></div>}
